# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fotoniks/Documents/Wahyu_Kinect/Wahyu_TA/gui/kinnect.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1310, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1310, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1310, 750))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.grpvImg1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.grpvImg1.setGeometry(QtCore.QRect(10, 10, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpvImg1.sizePolicy().hasHeightForWidth())
        self.grpvImg1.setSizePolicy(sizePolicy)
        self.grpvImg1.setMinimumSize(QtCore.QSize(640, 480))
        self.grpvImg1.setMaximumSize(QtCore.QSize(640, 480))
        self.grpvImg1.setObjectName("grpvImg1")
        self.grpvImg2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.grpvImg2.setGeometry(QtCore.QRect(660, 10, 640, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpvImg2.sizePolicy().hasHeightForWidth())
        self.grpvImg2.setSizePolicy(sizePolicy)
        self.grpvImg2.setMinimumSize(QtCore.QSize(640, 480))
        self.grpvImg2.setMaximumSize(QtCore.QSize(640, 480))
        self.grpvImg2.setObjectName("grpvImg2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 560, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStrart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStrart.setObjectName("btnStrart")
        self.verticalLayout.addWidget(self.btnStrart)
        self.btnPause = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPause.setObjectName("btnPause")
        self.verticalLayout.addWidget(self.btnPause)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setGeometry(QtCore.QRect(899, 500, 401, 220))
        self.tableView.setMinimumSize(QtCore.QSize(401, 220))
        self.tableView.setMaximumSize(QtCore.QSize(401, 220))
        self.tableView.setObjectName("tableView")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 550, 166, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineTinggi = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineTinggi.setObjectName("lineTinggi")
        self.verticalLayout_2.addWidget(self.lineTinggi)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineSudut = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineSudut.setObjectName("lineSudut")
        self.verticalLayout_2.addWidget(self.lineSudut)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(680, 540, 166, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.radioButtongray = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtongray.setObjectName("radioButtongray")
        self.verticalLayout_4.addWidget(self.radioButtongray)
        self.radioButtonjet = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonjet.setObjectName("radioButtonjet")
        self.verticalLayout_4.addWidget(self.radioButtonjet)
        self.radioButtonTresh = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonTresh.setObjectName("radioButtonTresh")
        self.verticalLayout_4.addWidget(self.radioButtonTresh)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(490, 540, 160, 141))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.radioButtonRGB = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButtonRGB.setObjectName("radioButtonRGB")
        self.verticalLayout_5.addWidget(self.radioButtonRGB)
        self.radioButtonInfra = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButtonInfra.setObjectName("radioButtonInfra")
        self.verticalLayout_5.addWidget(self.radioButtonInfra)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kinnect Viewer"))
        self.btnStrart.setText(_translate("MainWindow", "Start"))
        self.btnPause.setText(_translate("MainWindow", "Pause"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Tinggi Kinnect"))
        self.label_2.setText(_translate("MainWindow", "Sudut Kinnect (0-30 deg)"))
        self.label_3.setText(_translate("MainWindow", "Layar 2"))
        self.radioButtongray.setText(_translate("MainWindow", "Citra Kedalaman (Gray)"))
        self.radioButtonjet.setText(_translate("MainWindow", "Citra Kedalaman (Jet)"))
        self.radioButtonTresh.setText(_translate("MainWindow", "Batas Ambang"))
        self.label_4.setText(_translate("MainWindow", "Layar 1"))
        self.radioButtonRGB.setText(_translate("MainWindow", "RGB"))
        self.radioButtonInfra.setText(_translate("MainWindow", "Infrared"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    

